spring:
  application:
    name: social-network-backend
  config:
    import: optional:file:../../../.env
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  liquibase:
    change-log: classpath:db/changelog/liquibase-master.xml
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
      enabled: true

upload_files:
  base-folder: ${BASE_FOLDER-UPLOAD}
  image-folder: ${IMAGE_FOLDER}

public-folder: ${PUBLIC_FOLDER}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  cloudinary-url: ${CLOUDINARY_URL}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

application:
  security:
    jwt:
      jwtSecret: ${JWT_SECRET}
      jwtExpirationMs: 86400000
      jwtRefreshExpirationMs: 86400000